### Welcome to day 15 of 30 days of python

-- Numpy  
-- 1D array  
-- 2D array  
-- 3D array    
-- Indexing & Slicing 
-- Reshaping, Concatenation   

-- mean  
-- median  
-- standard deviation  
  
NumPy is a powerful library for numerical computations in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures efficiently.  

[Learn More about Numpy](https://numpy.org/devdocs/user/absolute_beginners.html)

What is array?

In computer programming, an array is a structure for storing and retrieving data.

Mini Project

Temperature Data Analysis
Generate random temperature data for 30 days and calculate the mean, median, and standard deviation of the temperature over the month. Also, find the days with temperatures above the average.

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.2'

In [3]:
type([1, 2, 3])

list

In [12]:
arr = np.array([0, 6, 5, 1, 2, 3])
type(arr)

numpy.ndarray

In [8]:
arr.shape

(3,)

In [15]:
print(np.std(arr))

2.1147629234082532


In [54]:
arr2d = np.array(
[
    [5, 0, 4], 
    [2, 9, 6]
]
)
arr2d.ndim

2

In [23]:
arr2d.size

6

In [26]:
print(np.median(arr2d))

4.0


In [ ]:
# slicing and indexing

In [29]:
# sorting
print(np.sort(arr)[2])

2


In [30]:
arr_sorted = np.sort(arr)

In [31]:
arr_sorted

array([0, 1, 2, 3, 5, 6])

In [32]:
print(arr_sorted[-1])

6


In [33]:
arr_sorted[-2:]

array([5, 6])

In [36]:
arr_sorted[4:]

array([5, 6])

In [35]:
arr_sorted[4:5+1]

array([5, 6])

In [48]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [40]:
arr2d[0]

array([2, 3, 4])

In [44]:
print(arr2d[0][2])

4


In [43]:
arr2d[0][-1]

np.int64(4)

In [41]:
arr2d[0].ndim

1

In [49]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [52]:
arr2d[1][1:]

array([7, 8])

In [53]:
arr2d[1][-2:]

array([7, 8])

In [50]:
arr2d[1][-1]

np.int64(8)

In [51]:
arr2d[1][2]

np.int64(8)

In [55]:
arr2d

array([[5, 0, 4],
       [2, 9, 6]])

In [56]:
np.sort(arr2d)

array([[0, 4, 5],
       [2, 6, 9]])

In [66]:
arr3d = np.array(
    [
        [[1, 2, 3],[3, 4, 6]],
        [[4, 5, 6],[5, 6, 8]]
    ]
)

arr3d.ndim

3

In [65]:
arr3d

array([[[1, 2, 3],
        [3, 4, 6]],

       [[4, 5, 6],
        [5, 6, 8]]])

In [74]:
arr3d[1][0][1:]

array([5, 6])

In [72]:
print(arr3d[1][1][-1])

8


In [70]:
arr3d[1].ndim

2

In [68]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.ndim

1

In [77]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
arr.reshape(2, 3, 1).ndim

3

In [82]:
arr1 = np.ones(5)
arr2 = np.zeros(5)

In [85]:
arr_con = np.concat((arr1, arr2))

In [86]:
arr_con.size

10

In [42]:
import numpy as np

In [43]:
np.__version__

'2.1.1'

In [44]:
type([1, 2, 3])

list

In [ ]:
0, 1,2,3, 5, 6

In [80]:
arr = np.array([0, 6, 5, 1, 2, 3])
type(arr)

numpy.ndarray

In [49]:
arr.shape

(3,)

In [55]:
print(np.std(arr))

2.1147629234082532


In [115]:
arr2d = np.array(
    [
        [5, 0, 4], 
        [2, 9, 6]
    ]
    )

arr2d.ndim


2

In [73]:
np.median(arr2d)

np.float64(3.0)

In [74]:
# slicing and indexing

In [85]:
arr_sorted = np.sort(arr)

In [83]:
# sorting

print(np.sort(arr)[2])


2


In [86]:
arr_sorted

array([0, 1, 2, 3, 5, 6])

In [88]:
print(arr_sorted[-1])

6


In [89]:
arr

array([0, 6, 5, 1, 2, 3])

In [90]:
arr_sorted

array([0, 1, 2, 3, 5, 6])

In [91]:
arr_sorted[-2:]

array([5, 6])

In [93]:
arr_sorted[4:5+1]

array([5, 6])

In [96]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [103]:
print(arr2d[0][2])

4


In [104]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [108]:
arr2d[1][1:]

array([7, 8])

In [116]:
np.sort(arr2d)

array([[0, 4, 5],
       [2, 6, 9]])

In [118]:
arr3d = np.array(
    [
    [[1, 2, 3],[3, 4, 6]],
    [[4, 5, 6],[5, 6, 8]]
    ]
    )

arr3d.ndim

3

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [121]:
x = np.array([
    [[], [], []], 
    [[], [], []], 
    [[], [], []]
])

x.ndim

3

In [119]:
arr3d

array([[[1, 2, 3],
        [3, 4, 6]],

       [[4, 5, 6],
        [5, 6, 8]]])

In [133]:
print(arr3d[1][1][-1])

8


In [142]:
arr3d[1][0][1:]

array([5, 6])

In [152]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.ndim

1

In [157]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
arr.reshape(2, 3, 1).ndim

3

In [174]:
arr1 = np.ones(5)
arr2 = np.zeros(5)

In [176]:
arr_con = np.concat((arr1, arr2))

In [177]:
arr_con.size

10

In [88]:
# mini project

# Temperature Data Analysis

weather = np.random.uniform(22, 38, 30)
weather

array([23.4812949 , 30.53094586, 28.71399204, 25.32353067, 23.09243436,
       36.92294649, 24.94779048, 28.05479227, 31.34088027, 31.37753335,
       31.04020647, 27.63732841, 36.49760079, 37.9921639 , 30.48877955,
       33.19919553, 30.09717578, 27.57913597, 26.55711066, 35.54023104,
       25.73857683, 33.8277976 , 28.40815392, 24.25351755, 37.42876996,
       26.15512269, 31.6681245 , 25.0322389 , 35.96694765, 28.06694974])

In [89]:
# mean

w_mean = np.mean(weather)
print(w_mean)

29.898708937167637


In [90]:
# median

w_median = np.median(weather)
print(w_median)

29.40558390569003


In [91]:
# standard deviation

w_std = np.std(weather)
print(w_std)

4.364347158770073


In [93]:
# Range
hot_days = weather[weather > w_mean]

array([30.53094586, 36.92294649, 31.34088027, 31.37753335, 31.04020647,
       36.49760079, 37.9921639 , 30.48877955, 33.19919553, 30.09717578,
       35.54023104, 33.8277976 , 37.42876996, 31.6681245 , 35.96694765])